---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install packages for Ansible support
    raw: dnf -y -e0 -d0 install python python-dnf libselinux-python

- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Update all packages
    dnf: name=* state=latest
  - name: Ensuring certain packages
    dnf: name={{ item }} state=present
    with_items:
    - git
    - zsh
    - ruby
    - rubygems
    - emacs
    - python-setuptools
    - python-pip
    - python-wheel
    - redhat-rpm-config
    - python-devel
  roles:
  - docker

- hosts: all
  become: yes
  tasks:
  - name: Set default shell
    user: name=vagrant shell=/bin/zsh groups=docker append=yes

- hosts: all
  tasks:
  - name: Install antigen
    git: repo=https://github.com/zsh-users/antigen.git dest="{{ ansible_env.HOME }}/config/antigen"
  - name: Install homesick
    gem: name=homesick state=latest
  - name: Check if dotfiles already cloned
    shell: homesick status dotfiles
    register: result
    ignore_errors: true
    changed_when: "result.rc != 0"
  - name: Configure castle
    shell: homesick clone malkarouri/dotfiles
    when: result|failed
  - name: Configure castle
    shell: homesick symlink dotfiles
  - name: Install nix
    shell: curl https://nixos.org/nix/install | sh
