---
- hosts: all
  become: yes
  gather_facts: false
  tasks:
  - name: Install packages for Ansible support
    raw: dnf -y -e0 -d0 install python python-dnf

- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: Install packages
    dnf: name={{ item }} state=present
    with_items:
    - git
